engine: Elasticsearch
kafka_configuration:
    bootstrap_server: localhost:9092
    topic: hardware-streaming
    group_id: hardware
information_format:
    temperature: 0
    ram_memory_format: 0
    cpu_usage_format: 0
    gpu_usage_format: 0
    hdd_usage_format: 0
    ethernet_usage_format: 0
